# Generated by Django 6.0.4 on 2026-04-20 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='email',
        ),
    ]
